language: python
sudo: required
dist: xenial
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
install:
  - pip install .
before_script:
  - sudo ./.travis-setup.sh "$USER"
script:
  - python setup.py test
notifications:
  email:
    - benchexec-dev@googlegroups.com
