language: python
sudo: required
dist: xenial
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
install:
  - pip install .
  - pip install black
before_script:
  - sudo ./.travis-setup.sh "$USER"
  # Disable one specific test that often fails on Travis.
  # This is due to a deadlock in the Python interpreter or used libraries
  # and there is nothing we can do. Luckily on new Python it does not occur.
  - sed -i benchexec/test_integration/__init__.py -e '/test_simple_parallel/ i \    @unittest.skipIf(sys.version_info < (3,7), "Fails nondeterministically if load is high")'
script:
  - python setup.py test
  - black . --check --diff
notifications:
  email:
    - benchexec-dev@googlegroups.com
