language: python
sudo: required
dist: trusty
python:
  - "2.7"
  - "3.4"
  - "3.5"
install:
  - pip install lxml pyyaml
  - pip install .
before_script:
  - sudo ./.travis-setup.sh "$USER" "$BENCHEXEC_TEST_USER"
env:
  - BENCHEXEC_TEST_USER=benchmarks
script:
  - python setup.py test
notifications:
  email:
    - benchexec-dev@googlegroups.com
