# This file is part of BenchExec, a framework for reliable benchmarking:
# https://github.com/sosy-lab/benchexec
#
# SPDX-FileCopyrightText: 2023 Dirk Beyer <https://www.sosy-lab.org>
#
# SPDX-License-Identifier: Apache-2.0

name: JavaScript Pipeline

on: [push, pull_request, workflow_dispatch]

jobs:
  lint:
    name: Perform linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts"

      - name: Cache node modules
        uses: actions/cache@v3
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-cache-node-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-cache-node-modules-
            ${{ runner.os }}-

      - name: Install dependencies
        run: npm ci
        working-directory: benchexec/tablegenerator/react-table

      - name: Lint
        run: npm run lint
        working-directory: benchexec/tablegenerator/react-table

  tests:
    name: Running tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2

      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: benchexec/tablegenerator/react-table/node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-

      - name: Install dependencies
        run: npm ci
        working-directory: benchexec/tablegenerator/react-table

      - name: Run tests
        run: npm run test
        working-directory: benchexec/tablegenerator/react-table

  javascript-build:
    name: Building the application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2

      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: benchexec/tablegenerator/react-table/node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-

      - name: Install dependencies
        run: npm ci
        working-directory: benchexec/tablegenerator/react-table

      - name: Build
        run: |
          npm run build
          git diff --stat --exit-code
        working-directory: benchexec/tablegenerator/react-table
